export const Data = [
  {
    id: "1",
    name: "RITTER SPORT Cornflakes 100g",
    image: "/chocolate1.png",
    unit_price: "5500",
    count_in_box: "10",
    box_price: "55000",
    sort: "ӨНГӨ ТӨРӨЛ",
    border: "#EAD70E",
    bg: "#FFC300",
  },
  {
    id: "3",
    name: "RITTER SPORT Raisins Hazelnuts 100g",
    unit_price: "5500",
    count_in_box: "12",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
    image: "/chocolate3.png",
  },
  {
    id: "4",
    name: "RITTER SPORT Marzipan 100g",
    unit_price: "5500",
    count_in_box: "12",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
    image: "/chocolate4.png",
  },
  {
    id: "5",
    name: "RITTER SPORT Praline 100g",
    unit_price: "5500",
    count_in_box: "13",
    box_price: "71500",
    image: "/chocolate5.png",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "6",
    name: "RITTER SPORT Peppermint 100g",
    unit_price: "5500",
    count_in_box: "12",
    box_price: "66000",
    image: "/chocolate6.png",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "7",
    name: "RITTER SPORT Butter Biscuit 100g",
    unit_price: "5500",
    count_in_box: "11",
    image: "/chocolate7.png",
    box_price: "60500",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "8",
    name: "RITTER SPORT Strawberry Yoghurt 100g",
    unit_price: "5500",
    count_in_box: "12",
    image: "/chocolate8.png",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "9",
    name: "RITTER SPORT Cocoa Mousse 100g",
    unit_price: "5500",
    count_in_box: "11",
    image: "/chocolate9.png",
    box_price: "60500",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "10",
    name: "RITTER SPORT Hazelnuts 100g",
    unit_price: "5500",
    image: "/chocolate10.png",
    count_in_box: "12",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "11",
    name: "RITTER SPORT Dark Almond Orange  100g",
    unit_price: "5500",
    count_in_box: "12",
    image: "/chocolate11.png",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "12",
    name: "RITTER SPORT Rum Raisins Hazelnut 100g",
    unit_price: "5500",
    image: "/chocolate12.png",
    count_in_box: "12",
    box_price: "66000",
    sort: "ӨНГӨ ТӨРӨЛ",
  },
  {
    id: "13",
    name: "RITTER SPORT Whole Hazelnuts 100g",
    unit_price: "5500",
    count_in_box: "10",
    image: "/chocolate13.png",
    box_price: "55000",
    sort: "САМРЫН СОНГОЛТ",
  },
  {
    id: "14",
    name: "RITTER SPORT Dark Whole Hazelnuts 100g",
    unit_price: "5500",
    count_in_box: "10",
    image: "/chocolate14.png",
    box_price: "55000",
    sort: "САМРЫН СОНГОЛТ",
    bg: "#C70039",
  },
  {
    id: "15",
    name: "RITTER SPORT Whole Almonds 100g",
    unit_price: "5500",
    image: "/chocolate15.png",
    count_in_box: "11",
    box_price: "60500",
    sort: "САМРЫН СОНГОЛТ",
    bg: "#1A6D22",
  },
  {
    id: "16",
    name: "RITTER SPORT Honey Salt Almonds 100g",
    unit_price: "5500",
    image: "/chocolate16.png",
    count_in_box: "11",
    box_price: "60500",
    sort: "САМРЫН СОНГОЛТ",
    bg: "#D18715",
  },
  {
    id: "17",
    name: "RITTER SPORT Cashew 100g",
    unit_price: "5500",
    image: "/chocolate17.png",
    count_in_box: "12",
    box_price: "66000",
    sort: "САМРЫН СОНГОЛТ",
  },
  {
    id: "18",
    name: "RITTER SPORT Dark Whole Almonds 100g",
    unit_price: "5500",
    image: "/chocolate18.png",
    count_in_box: "11",
    box_price: "60500",
    sort: "САМРЫН СОНГОЛТ",
  },
  {
    id: "19",
    name: "RITTER SPORT 55% SMOOTH from Ghana 100g",
    image: "/chocolate19.png",
    unit_price: "5500",
    count_in_box: "12",
    box_price: "66000",
    sort: "КАКАО СОНГОЛТ",
  },
  {
    id: "20",
    name: "RITTER SPORT 61% FINE from Nicaragua 100g",
    unit_price: "5500",
    image: "/chocolate20.png",

    count_in_box: "12",
    box_price: "66000",
    sort: "КАКАО СОНГОЛТ",
  },
  {
    id: "21",
    name: "RITTER SPORT 74% INTENSE from Peru 100g",
    unit_price: "5500",
    count_in_box: "12",
    image: "/chocolate21.png",
    box_price: "66000",
    sort: "КАКАО СОНГОЛТ",
  },
  {
    id: "22",
    name: "RITTER SPORT Alpine Milk Chocolate 250g",
    unit_price: "13500",
    image:
      "https://irp.cdn-website.com/6cb74a62/dms3rep/multi/NEW_AlpineMilk_Normal.webp",
    count_in_box: "11",
    box_price: "119900",
    sort: "250 гр БАР",
  },
  {
    id: "23",
    name: "RITTER SPORT Hazelnuts 250g",
    unit_price: "13500",
    image:
      "https://irp.cdn-website.com/6cb74a62/dms3rep/multi/NEW_Hazelnuts_Normal.webp",
    count_in_box: "11",
    box_price: "119900",
    sort: "250 гр БАР",
  },
  {
    id: "24",
    name: "RITTER SPORT PRALINE 250g",
    unit_price: "10900",
    image:
      "https://irp.cdn-website.com/6cb74a62/dms3rep/multi/NEW_Praline_Normal.webp",
    count_in_box: "11",
    box_price: "119900",
    sort: "250 гр БАР",
  },
  {
    id: "25",
    name: "RITTER SPORT Gold Edition 250g",
    image: "/chocolate25.webp",
    count_in_box: "11",
    box_price: "119900",
    sort: "250 гр БАР",
  },
  {
    id: "26",
    name: "RITTER SPORT Yogurt Mix/Joghurt Schatz 176g",
    image: "/chocolate26.png",
    unit_price: "13500",
    count_in_box: "8",
    box_price: "108000",
    sort: "CHOCO шоо",
  },
  {
    id: "27",
    name: "RITTER SPORT Happy birthday/Lass Dich Feiern 176g ",
    count_in_box: "8",
    image: "/chocolate27.png",
    box_price: "108000",
    sort: "CHOCO шоо",
  },
  {
    id: "28",
    name: "RITTER SPORT Mini Alpine Milk 2 Pack 33.34g",
    unit_price: "2800",
    count_in_box: "16",
    box_price: "44800",
    image: "/chocolate28.png",

    sort: "MINI RANGE",
  },
  {
    id: "29",
    name: "RITTER SPORT Mini Whole Hazelnuts 2 Pack 33.34g",
    unit_price: "2800",
    count_in_box: "16",
    image: "/chocolate29.png",
    box_price: "44800",
    sort: "MINI RANGE",
  },
  {
    id: "30",
    name: "RITTER SPORT Mini САМРЫН СОНГОЛТ 116,69g",
    unit_price: "11000",
    image: "/chocolate30.png",
    count_in_box: "8",
    box_price: "88000",
    sort: "MINI RANGE",
  },
  {
    id: "31",
    name: "RITTER SPORT Mini Chocolate Mix 133,36g",
    unit_price: "11000",
    image: "/chocolate31.png",
    count_in_box: "8",
    box_price: "88000",
    sort: "MINI RANGE",
  },
];
